"""Central schema and semantic-audit file registry.

The weekly semantic audit uses this module as the local source of truth for
expected CSV headers and the files that define model, metric, source, mapping,
dashboard, and documentation behavior.
"""

EXPECTED_CSV_SCHEMAS: dict[str, list[str]] = {
    "data/fixtures.csv": [
        "match_id",
        "date_utc",
        "time_utc",
        "competition",
        "group",
        "home",
        "away",
        "venue",
        "city",
        "country",
    ],
    "data/team_ratings.csv": [
        "team",
        "elo",
        "attack",
        "defense",
        "recent_form",
        "fifa_rank_proxy",
        "training_temp_c",
        "training_humidity_pct",
        "data_quality",
        "last_updated",
        "notes",
    ],
    "data/team_name_aliases.csv": [
        "alias",
        "canonical",
    ],
    "data/historical_matches.csv": [
        "match_id",
        "date_utc",
        "competition",
        "competition_type",
        "team",
        "opponent",
        "is_home",
        "is_neutral",
        "venue",
        "city",
        "country",
        "team_goals",
        "opponent_goals",
        "team_xg",
        "opponent_xg",
        "shots_for",
        "shots_against",
        "shots_on_target_for",
        "shots_on_target_against",
        "possession_pct",
        "opponent_elo",
        "team_elo_pre",
        "temperature_c",
        "humidity_pct",
        "altitude_m",
        "wind_kmh",
        "precipitation_mm",
        "roof_closed",
        "source",
        "last_updated",
    ],
    "data/team_behavior.csv": [
        "team",
        "reference_date",
        "behavior_window_start",
        "behavior_window_end",
        "matches_available_all_time",
        "matches_used_recent",
        "oldest_match_used",
        "latest_match_used",
        "behavior_config_name",
        "n_matches",
        "weighted_goals_for",
        "weighted_goals_for_raw",
        "weighted_goals_for_adjusted",
        "weighted_goals_against",
        "weighted_goals_against_raw",
        "weighted_goals_against_adjusted",
        "weighted_goal_difference",
        "all_time_goals_for",
        "all_time_goals_against",
        "attack_index",
        "attack_index_raw",
        "attack_index_adjusted_old",
        "attack_index_adjusted",
        "attack_index_residual",
        "attack_index_residual_raw",
        "attack_index_residual_robust",
        "attack_index_final",
        "defense_index",
        "defense_index_raw",
        "defense_index_adjusted_old",
        "defense_index_adjusted",
        "defense_index_residual",
        "defense_index_residual_raw",
        "defense_index_residual_robust",
        "defense_index_final",
        "weighted_goal_for_residual",
        "weighted_goal_for_residual_raw",
        "weighted_goal_for_residual_robust",
        "weighted_goal_against_residual",
        "weighted_goal_against_residual_raw",
        "weighted_goal_against_residual_robust",
        "weighted_result_residual",
        "residual_coverage_recent",
        "mean_blowout_weight_recent",
        "top_3_attack_residual_share",
        "top_3_defense_residual_share",
        "recent_form_index",
        "weighted_btts_rate",
        "weighted_over_2_5_rate",
        "clean_sheet_rate",
        "failed_to_score_rate",
        "environment_response_index",
        "environment_sample_size",
        "attack_data_quality",
        "defense_data_quality",
        "form_data_quality",
        "environment_data_quality",
        "overall_data_quality",
        "behavior_warning",
        "sample_size_warning",
        "staleness_warning",
        "opponent_quality_warning",
        "mean_opponent_elo_recent",
        "median_opponent_elo_recent",
        "min_opponent_elo_recent",
        "max_opponent_elo_recent",
        "opponent_elo_coverage_recent",
        "strong_opponent_match_count",
        "weak_opponent_match_count",
        "schedule_strength_label",
        "schedule_strength_warning",
        "opponent_adjustment_warning",
        "residual_warning",
        "residual_concentration_warning",
        "last_updated",
    ],
    "data/venues.csv": [
        "venue",
        "city",
        "country",
        "latitude",
        "longitude",
        "altitude_m",
        "temp_c",
        "humidity_pct",
        "wind_kmh",
        "precipitation_mm",
        "roof_expected_closed",
        "neutral_site",
    ],
    "data/market_odds.csv": [
        "match_id",
        "market",
        "selection",
        "odds",
        "source",
        "last_updated",
    ],
    "data/polymarket_markets.csv": [
        "market_id",
        "question",
        "slug",
        "event_title",
        "category",
        "start_date",
        "end_date",
        "active",
        "closed",
        "outcomes",
        "yes_price",
        "no_price",
        "liquidity",
        "volume",
        "source",
        "last_updated",
    ],
    "data/market_mappings.csv": [
        "match_id",
        "market_id",
        "market_type",
        "model_side",
        "polymarket_side",
        "manual_confirmed",
        "notes",
    ],
    "data/prediction_log.csv": [
        "timestamp_utc",
        "match_id",
        "home",
        "away",
        "kickoff_utc",
        "market_id",
        "question",
        "market_type",
        "model_side",
        "polymarket_side",
        "model_probability",
        "fair_price_cents",
        "polymarket_price_cents",
        "alpha_gap_cents",
        "alpha_ev",
        "signal_strength",
        "home_xg",
        "away_xg",
        "model_config_name",
        "mapping_confidence",
        "liquidity",
        "volume",
    ],
    "data/results_log.csv": [
        "match_id",
        "home",
        "away",
        "home_goals",
        "away_goals",
        "result_home_win",
        "result_draw",
        "result_away_win",
        "over_2_5",
        "under_2_5",
        "btts_yes",
        "btts_no",
        "completed",
        "result_source",
        "last_updated",
    ],
}

MODEL_DEFINITION_FILES: set[str] = {
    "src/model.py",
    "src/ratings.py",
    "src/climate.py",
    "src/weather.py",
    "src/historical_data.py",
    "src/historical_ingestion.py",
    "src/football_api.py",
    "src/team_names.py",
    "src/team_behavior.py",
    "src/recency.py",
    "src/behavior_calibration.py",
    "src/behavior_driver_report.py",
    "src/elo.py",
    "src/elo_calibration.py",
    "src/performance_residuals.py",
    "src/environment_response.py",
}

METRIC_DEFINITION_FILES: set[str] = {
    "src/model.py",
    "src/alpha.py",
    "src/sensitivity.py",
    "src/backtesting.py",
    "src/report_metrics.py",
    "src/market_tables.py",
    "src/team_behavior.py",
    "src/environment_response.py",
    "src/recency.py",
    "src/behavior_calibration.py",
    "src/behavior_driver_report.py",
    "src/elo.py",
    "src/elo_calibration.py",
    "src/performance_residuals.py",
    "src/historical_ingestion.py",
}

API_SOURCE_FILES: set[str] = {
    "src/config.py",
    "src/data_sources.py",
    "src/weather.py",
    "src/odds.py",
    "src/polymarket.py",
    "src/cache.py",
    "src/historical_data.py",
    "src/historical_ingestion.py",
    "src/football_api.py",
    "src/team_names.py",
    "src/team_behavior.py",
    "src/elo.py",
}

POLYMARKET_MAPPING_FILES: set[str] = {
    "src/polymarket.py",
    "src/market_mapping.py",
    "src/alpha.py",
    "data/polymarket_markets.csv",
    "data/market_mappings.csv",
}

DASHBOARD_DEFINITION_FILES: set[str] = {
    "app.py",
    "src/report_charts.py",
    "src/report_metrics.py",
    "src/market_tables.py",
    "src/timeline.py",
}

DOCUMENTATION_FILES: set[str] = {
    "README.md",
    "AGENTS.md",
}

SEMANTIC_LAYER_DOCUMENTS: set[str] = {
    "~/.codex/skills/worldcup-alpha-model-semantic-layer/SKILL.md",
    "~/.codex/skills/worldcup-alpha-model-semantic-layer/references/semantic-layer.md",
    "~/.codex/skills/worldcup-alpha-model-semantic-layer/references/source-inventory.md",
    "~/.codex/skills/worldcup-alpha-model-semantic-layer/references/evidence.md",
}


def validate_historical_matches_schema(df) -> list[str]:
    return _validate_schema(df, "data/historical_matches.csv")


def validate_team_behavior_schema(df) -> list[str]:
    return _validate_schema(df, "data/team_behavior.csv")


def _validate_schema(df, schema_name: str) -> list[str]:
    expected = EXPECTED_CSV_SCHEMAS[schema_name]
    if df is None:
        return [f"{schema_name}: dataframe is missing; expected columns: {', '.join(expected)}"]
    try:
        columns = list(df.columns)
    except Exception as exc:
        return [f"{schema_name}: could not inspect columns: {exc}"]
    missing = [col for col in expected if col not in columns]
    warnings: list[str] = []
    if missing:
        warnings.append(f"{schema_name}: missing columns: {', '.join(missing)}")
    return warnings
